# Generated by Django 5.2.3 on 2025-06-22 19:03

from django.db import migrations


def seed_currency(apps, schema_editor):
    Currency = apps.get_model("rates", "Currency")
    Currency.objects.bulk_create(
        [
            Currency(currency="Real Brasileiro", symbol="BRL"),
            Currency(currency="Dólar Americano", symbol="USD"),
            Currency(currency="Euro", symbol="EUR"),
            Currency(currency="Iene Japonês", symbol="JPY"),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_currency),
    ]
