version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - env_example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - env_example
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
